language: csharp
solution: PVM.NET.sln
sudo: required
script:
  - xbuild /p:Configuration=Release PVM.NET.sln
  - nunit-console bin/Release/PVM.Core.Test.dll
before_install:
  - sudo apt-get install nunit-console
before_script:
  - nuget restore PVM.NET.sln
  
env:
  global:
   # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
   #   via the "travis encrypt" command using the project repo's public key
   - secure: "NmY9Pun0fam3T2TovrmBJog6hIdUm0CzIr0bxAW9RURPP/L2zXrjI5BLEBs2o4c7xzqpKAJeMNGmVA3yMBtcGFtHtD3ZCjuvvyegR7PYx3AjxOzgpnZKGURg+VVXpUi3nzbcMRdbdAXQrO9dIWk1WITXjrZm56GyMnbQJPeBj40UizmC/AhQbTYO17Ruu3Vh1DvGtL6QU+1hOJLaRljNMuOaZg5YssBvIOLY+to4SbePRzRto8zQRrWo/llA+PckMwfMXe9DY9tCP2tuDYHyUe+wHOgydblIXKX63sdQNbhyjV/tthkMT5BfuWekjMQ3xLFkfpLevygW3ZAEBzoCs3NMq/OyBqByW22v0maiIjt4l6CbaxATNDS4V7vVpPnp9nC/7kEHd0o68j5kiIqoBg9+Fz5eJ5GjpqpIq3StJLujYU6IcAtj22jIIrfyny7fi6VlNRO0JkoqOZjwv4uqiaVlyt04e7YGsnsfDyh1/gJLiPJZ4BKnnnYnVUZllusggrVDHAuXPaztDFxhDfhXG7Rw+BIB2IHlp1LaXw2ikLOu42ccOkUh6rITFiQGVHHCNwiKbA95oDhOKvPK7Zak+BkDfbDn3grOy4METwwd/6EYCDFXDPRYKm6ostcCQlapNqnYQ0c2nijwhRti2RsiaO25Rsv+jTeGa6EF8oL0nks="

addons:
  coverity_scan:
    project:
      name: "dkschlos/PVM.NET"
      description: "Build submitted via Travis CI"
    notification_email: dominik.schlosser@gmail.com
    build_command_prepend: "MSBuild.exe /t:Clean;.\.nuget\nuget.exe restore .\PVM.NET.sln"
    build_command:   "MSBuild.exe /t:Rebuild"
    branch_pattern: coverity_scan
