language: csharp
solution: PVM.NET.sln
sudo: required
script:
  - xbuild /p:Configuration=Release PVM.NET.sln
  - nunit-console bin/Release/PVM.Core.Test.dll
before_install:
  - sudo apt-get install nunit-console
before_script:
  - nuget restore PVM.NET.sln
  
env:
  global:
   # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
   #   via the "travis encrypt" command using the project repo's public key
   - secure: "rG2IA2iF/GhG0NEKyDlQLzZs+U+y1vHzLqe2it5xNF50ycAcRaFPNoW7yvqN2xbJnlwLlA4AVs7eLiRlj0SdRRigXcJjoeufnrA0Ve/LldrEyE555wZMJE8jKIT8zccnjB494P89Hbki5Je+8QF12DAzi5CoVMPKRHUEliZH6TYNxaCnSeAHh8448HNUdy6ecXkUa+gTvL3Dn/SODDoSLTXVvOK4AOZBc/FOGxeAHdL48T0/W3TtwA9BL2j0FMFgS0ay0/Z6t2ezos94GjIxzbuiiKq1DmXxH088WywuBwQ0ILg6qRrutwU48IeHPGyyYJCXV/9eNOIGwOQdVxMfBl88xLB4FzzwdLcfzZEoqMTKgt6ZLeQLMx1q0jT7cMBXni4UcG6ez/X9fgK6GEu2QPdpTQsd+h1xIlMrKVSTW2gzMw8tdPM3MZG9RL4JYs3Xs+m9kMBHr0gLHsDGDyCZH5LTFpopNwtrRftIgNH4h6Db9hYd8LmTn+EbQzv7uMmAzHs/Rf1i130E5/QFC/EGR+9JmnsTlg6ab4O24KAsB2Yg2TKQ5d4JhovPfiq34ou7CfGu0xQUjXi0l5oIiBAg4UeyhOGvy6+yMt+BmkWIEqKSGrxAPLt98bKBd2MzpLm/PyIVMYXSus8Qm3BmvBQf/rR4l+s6EC3RTUt7tp2wnNY="

addons:
  coverity_scan:
    project:
      name: "dkschlos/PVM.NET"
      description: "Build submitted via Travis CI"
    notification_email: dominik.schlosser@gmail.com
    build_command_prepend: ".\\.msbuild\\msbuild.exe /t:Clean;.\\.nuget\\nuget.exe restore .\\PVM.NET.sln"
    build_command:   ".\\.msbuild\\msbuild.exe /t:Rebuild"
    branch_pattern: coverity_scan
