language: csharp
solution: PVM.NET.sln
sudo: false
script:
  - xbuild /p:Configuration=Release PVM.NET.sln
before_install:
  - sudo apt-get install nunit-console
before_script:
  - nuget restore PVM.NET.sln
after_script:
  - nunit-console test/PVM.Core.Test/bin/Release/PVM.Core.Test.dll
